### ISSUE TITLE
[BUG] 1.20.3 cannot open file

### ISSUE THREAD

**Issue by qazxcdswe123** [scambier/obsidian-omnisearch#338]
**Problem description:**

```
Uncaught TypeError: Cannot read properties of undefined (reading 'offset')
    at H (plugin:omnisearch:49:2915)
    at D (plugin:omnisearch:49:2754)
    at hs.emit (plugin:omnisearch:6:8419)
    at Object.eval [as func] (plugin:omnisearch:50:4163)
    at e.handleKey (app.js:1:743120)
    at e.onKeyEvent (app.js:1:744376)
```

It seems that if the title is matched, it fails to open it. And only some (presumably title matched file) cannot be opened. Not totally sure though.

I'm currently preparing for exams and don't have enough time to investigate it. But i can confirm that revert to 1.20.2 fix this issue.

Thanks!

**Comment by scambier** [comment]
Thanks!
